POST, GET, GETByID, PATCH e DELETE quotations feito
TukozakiT/happy-puppy-catalog-backend pull request #10
Opened 2022-09-28 12:59 UTC by izabelass

Tive que adicionar um { required: false } no email do schema pois sem ele, quando estava fazendo o patch, tava 

Estou com dois problemas:

1. o update ta extendendo a interface do createQuotation, mas não parece estar funcionando corretamente. Exemplo: se eu mudar o valor da propriedade “quantity”, que deve ser um numero, para uma string “10”, não apresenta nenhum erro; mas se eu mudar para “teste” aparece o seguinte erro:
{
	"statusCode": 500,
	"message": "Internal server error"
}

2. o parametro do patch, do getById e do Delete é o id. Se na requisicao eu colocar um id que nao existe, mas que possui a mesma length dos outros e a estrutura é a mesma (substituir num por num, letra por letra), aparece o erro corretamente: 
{
	"statusCode": 404,
	"message": "Orçamento #6333906b5696ee8472a39b62 não encontrado",
	"error": "Not Found"
}

Mas se eu colocar caracteres a mais ou a menos ou mudar o tipo/ordem de char do id do request aparece esse erro:
{
	"statusCode": 500,
	"message": "Internal server error"
}

2022-09-28 14:56 UTC, TukozakiT requested changes
Primeiro, sobre os erros 500, pq ele está acontecendo? Pq eu esqueci de colocar os validators no DTO. (Vou comitar a versão corrigida p vc ver).
E pq retorna 500 em vez de 404? Pq qndo vc dava o comando de acessar o mongoDB, o mongoDB dava erro pq no shcema dele tá errado, aí dava ruim no server e então retornava 500. 
Essa parte é relacionada também ao segundo erro (qndo vc digitava um _id q n existe)
Para resolver isso, coloquei um try catch no service na hora de consultar o BD.
Caso desse erro, retornaria o problema do BD.

Outro comentário é sobre quando não se encontra nenhum dado.
O erro 404 é para quando não se encontra o endpoint. Exemplo se a pessoa tentar acessar um endpoint "quotatiooon" (erro de digitação)
    então a API vai dizer q n existe quotatiooon e vai dar 404.
    já para quando dá certo, ela tem que retornar um 200-299 pq tá OK, ela n errou nada, o servidor está funcionando normal.
    Como o corpo está vazio, tem 2 abordagens possívels: 
    1- simplesmente enviar um dataQuotation vazio, e o front vai se virar com essa info vazia;
    2- enviar um 204 NO CONTENT

2022-09-28 15:29 UTC, TukozakiT commented
Eu subi algumas alterações aqui. e dá um **npm install** pra atualizar as dependencias, pq eu instalei o validator.
1- no DTO eu alterei adicionando os validators (eles são decorators, usando "@" nome do tipo
2- no controller observe o que eu fiz no findOne(), que pode retornar um 204 caso tenha problema. Na vdd se pá a gente nem precisa usar o "@res response", pq o NestJS já joga as exeptions nativamente, sem a gente precisar ficar definindo no controller. A gente só precisa desse @res quando vai usar o erro 204 pq não é nativo do NESTJS
3- Nos services eu coloquei vários comentários, leia lá e veja mais ou menos se vc entende minhas explicações kkkkk

2022-10-03 16:32 UTC, izabelass commented
No DTO, ProductDetails eu troquei o unityPrice por number

O restante fiz conforme as instruções. Fiz os testes e aparentemente está funcionando.

2022-10-03 16:49 UTC, TukozakiT approved these changes

2022-10-03 16:50 UTC, TukozakiT commented
Testado e aprovado. Parabéns, tudo está funcionando, inclusive o tratamento de erros e exceções.

2022-10-03 16:51 UTC, merged